openapi: 3.0.3

info:
  title: Demo
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /api/v1/demo:
    $ref: './demo/demo.yml'

  /api/v1/cache/demo:
    $ref: './cache/demo/cache-demo.yml'

  /api/v1/cache/demo/cacheable:
    $ref: './cache/demo/cacheable-demo.yml'

  /api/v1/cache/demo/cache-put:
    $ref: './cache/demo/cache-put-demo.yml'